server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: root
      initial-size: 5
      min-idle: 5
      max-active: 10
      max-wait: 60000
      filters: stat

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lindp.springcloud.entity

eureka:
  client:
    # 表示是否将自己注册进EurekaServer
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment8002
    # 主机名显示IP信息，鼠标移动上去显示
    prefer-ip-address: true