server:
  port: 8001

spring:
  application:
    name: provider-hystrix-payment8001

eureka:
  client:
    # 表示是否将自己注册进EurekaServer
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
